### ISSUE TITLE
badgeos-badgestrack.po in French

### ISSUE THREAD

**Issue by cyclingzealot** [opencredit/BadgeOS-BadgeStack-Add-on#3]
Before I start working on it, just curious if anyone has translated BadgeStack to French.

**Comment by tw2113** [comment]
Not that I've ever seen. All the language files I know of are in https://github.com/opencredit/BadgeOS-BadgeStack-Add-on/tree/master/languages

**Comment by tw2113** [comment]
I also JUST pushed up a pot file that I generated quickly through Poedit. Hopefully that provides a great starting point.

**Comment by cyclingzealot** [comment]
Thanks.  I'll see if I can merge with credil/BadgeOS-BadgeStack-Add-on and use it.  The pot file I generated was using msgfilter and it was erroring out on the UTF-8 (which in turn, iconv didn't like certain curly quotes & curly double quotes)

**Comment by cyclingzealot** [comment]
Curious, what version of poedit are you using?   Mine doesn't seem to like multi-line strings.  I'm using poedit 1.4.6 on Ubuntu 12.

**Comment by tw2113** [comment]
I'm on 1.8.1 on OSX.
