### ISSUE TITLE
Extra ../../badgeos/ strings in languages/badgeos-badgestack.po file

### ISSUE THREAD

**Issue by cyclingzealot** [opencredit/BadgeOS-BadgeStack-Add-on#4]
This ticket can be classified as priority very low or closed.

I noticed in the languages/badgeos-badgestack.po file there were lots of strings from files in ../../badgeos/  included.  This had initially confused me when I "refreshed the catalogue from .POT" in Poedit as there were about 300 strings that were deemed outdated.  I thought it was something wrong with my version of poedit.    

Might want to refresh the English .po file.  I don't think it will cause conflict when I do a pull request as I'll be working on the french po file. 

But, I can do it in my version of the fork if you prefer.

**Comment by tw2113** [comment]
I'd just focus on the French copy. I'll take care of the English one.

**Comment by tw2113** [comment]
Removing the original english version in favor of the properly done .pot file.
